# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v3', '0002_auto_20170928_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='click',
            options={'verbose_name': 'Click', 'verbose_name_plural': 'Click'},
        ),
        migrations.AlterField(
            model_name='click',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Target'),
        ),
        migrations.AlterField(
            model_name='click',
            name='datetime',
            field=models.DateTimeField(verbose_name='Datetime'),
        ),
        migrations.AlterField(
            model_name='click',
            name='is_valid',
            field=models.NullBooleanField(default=None, verbose_name='Is Valid?'),
        ),
        migrations.AlterField(
            model_name='result',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='User Email'),
        ),
    ]
