# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v3', '0005_remove_result_survey_sleep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='http_request_sha1',
            new_name='request_sha1'
        ),
        migrations.AddField(
            model_name='result',
            name='status',
            field=models.CharField(choices=[('added', 'Added'), ('parsed', 'Parsed'), ('error', 'Error'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('recalculate', 'To Recalculate')], default='added', max_length=30, verbose_name='Status'),
        ),
    ]
