# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v3', '0008_result_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='survey_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, help_text='Celsius', max_digits=3, null=True, verbose_name='Temperature'),
        ),
    ]
