dist: bionic
language: python
python:
  - 3.8.5


addons:
  sonarcloud:
    organization: "astromatt"

jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.sonar/cache'

install:
  - pip install -r requirements.txt
  - pip freeze

script:
  - pycodestyle backend
  - python manage.py check
  - python manage.py test --verbosity=2

after_success:
  - sonar-scanner --debug
