# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Datetime')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('method', models.CharField(max_length=10, verbose_name='Method')),
                ('api_version', models.PositiveSmallIntegerField(verbose_name='API version')),
                ('data', models.TextField(blank=True, null=True, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
                'ordering': ['-datetime'],
            },
        ),
    ]
