# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20161231_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlogger',
            name='sha1',
            field=models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='SHA1'),
        ),
    ]
