# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 12:53
from __future__ import unicode_literals

import backend.logger.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_requestlogger_sha1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlogger',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PATCH', 'PATCH'), ('PUT', 'PUT'), ('HEAD', 'HEAD')], default='GET', max_length=10, verbose_name='Method'),
        ),
    ]
