# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_auto_20170915_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlogger',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Datetime'),
        ),
    ]
