# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0005_requestlogger_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTTPRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Datetime')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Datetime')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PATCH', 'PATCH'), ('PUT', 'PUT'), ('HEAD', 'HEAD')], default='GET', max_length=10, verbose_name='Method')),
                ('api_version', models.PositiveSmallIntegerField(verbose_name='API version')),
                ('data', models.TextField(blank=True, null=True, verbose_name='Data')),
                ('sha1', models.CharField(blank=True, default=None, max_length=40, null=True, unique=True, verbose_name='SHA1')),
            ],
            options={
                'verbose_name': 'HTTP Request',
                'verbose_name_plural': 'HTTP Requests',
            },
        ),
    ]
