# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0006_httprequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestLogger',
        ),
    ]
