# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0007_delete_requestlogger'),
    ]

    operations = [
        migrations.AddField(
            model_name='httprequest',
            name='data_status',
            field=models.CharField(blank=True, choices=[('production', 'Production'), ('test', 'Test')], default='production', max_length=30, null=True, verbose_name='Data status'),
        ),
    ]
