# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0009_auto_20170915_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httprequest',
            name='sha1',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=40, null=True, unique=True, verbose_name='SHA1'),
        ),
    ]
