# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0010_auto_20170915_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Datetime')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Datetime')),
                ('http_request_sha1', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='SHA1')),
            ],
            options={
                'verbose_name': 'Error',
                'verbose_name_plural': 'Errors',
            },
        ),
        migrations.AlterField(
            model_name='httprequest',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Datetime'),
        ),
    ]
