# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0011_auto_20170928_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlogger',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='errorlogger',
            name='traceback',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Traceback'),
        ),
    ]
