# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0013_auto_20171002_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errorlogger',
            old_name='http_request_sha1',
            new_name='request_sha1',
        ),
    ]
