# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0014_auto_20171003_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='httprequest',
            name='integrity',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('error', 'Error'), ('ok', 'OK')], default='unknown', max_length=30, verbose_name='Data integrity'),
        ),
    ]
