# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0015_httprequest_integrity'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlogger',
            name='request',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='logger.HTTPRequest', verbose_name='HTTP Request'),
        ),
    ]
