# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0016_errorlogger_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorlogger',
            name='request',
        ),
        migrations.AddField(
            model_name='httprequest',
            name='error_log',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Error Log'),
        ),
        migrations.DeleteModel(
            name='ErrorLogger',
        ),
    ]
