# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0005_experiment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiment',
            options={'ordering': ['-date'], 'verbose_name': 'Experiment', 'verbose_name_plural': 'Experiments'},
        ),
        migrations.AddField(
            model_name='experiment',
            name='blue_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='experiment_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='experiment_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='red_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='white_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
