# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0006_auto_20161008_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='blue_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='red_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='white_end',
            field=models.DateTimeField(null=True),
        ),
    ]
