# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiment', '0010_auto_20161011_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='attempt',
            field=models.PositiveSmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='click',
            name='background',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('blue', 'Blue'), ('red', 'Red')], max_length=15),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
