# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0011_auto_20161202_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
