# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_index=True, verbose_name='Datetime')),
                ('target', models.CharField(db_index=True, max_length=50, verbose_name='Target')),
                ('action', models.CharField(db_index=True, max_length=50, verbose_name='Action')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Datetime')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Age')),
                ('condition', models.CharField(max_length=50, verbose_name='Condition')),
                ('gender', models.CharField(max_length=50, verbose_name='Gender')),
                ('rhythm', models.CharField(max_length=50, verbose_name='Rhythm')),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(db_index=True, verbose_name='Start datetime')),
                ('end_datetime', models.DateTimeField(verbose_name='End datetime')),
                ('colors', models.CharField(max_length=50, verbose_name='Color order')),
                ('device', models.CharField(max_length=50, verbose_name='Device')),
                ('location', models.CharField(db_index=True, max_length=50, verbose_name='Location')),
                ('uid', models.EmailField(db_index=True, max_length=254, verbose_name='User ID')),
                ('polarization', models.CharField(max_length=50, verbose_name='Polarization')),
                ('timeout', models.FloatField(help_text='Seconds per color', verbose_name='Timeout')),
                ('regularity', models.PositiveSmallIntegerField(help_text='Click every X seconds', verbose_name='Reqularity')),
                ('attempt', models.PositiveSmallIntegerField(db_index=True, verbose_name='Attempt')),
            ],
            options={
                'verbose_name': 'Trial',
                'verbose_name_plural': 'Trials',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.AddField(
            model_name='survey',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.Trial', verbose_name='Trial'),
        ),
        migrations.AddField(
            model_name='event',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.Trial', verbose_name='Trial'),
        ),
    ]
