# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('target', models.CharField(db_index=True, max_length=50)),
                ('action', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.EmailField(db_index=True, max_length=254)),
                ('is_valid', models.NullBooleanField(default=None)),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('age', models.PositiveSmallIntegerField()),
                ('condition', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('rhythm', models.CharField(max_length=50)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField()),
                ('colors', models.CharField(max_length=50)),
                ('device', models.CharField(max_length=50)),
                ('location', models.CharField(db_index=True, max_length=50)),
                ('participant', models.EmailField(db_index=True, max_length=254)),
                ('polarization', models.CharField(max_length=50)),
                ('seconds', models.PositiveSmallIntegerField()),
                ('trial', models.PositiveSmallIntegerField(db_index=True)),
                ('count_all', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Count click events - all')),
                ('count_blue', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Count click events - blue')),
                ('count_red', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Count click events - red')),
                ('count_white', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Count click events - white')),
                ('percentage_all', models.FloatField(blank=True, null=True, verbose_name='Percentage coefficient - all')),
                ('percentage_blue', models.FloatField(blank=True, null=True, verbose_name='Percentage coefficient - blue')),
                ('percentage_red', models.FloatField(blank=True, null=True, verbose_name='Percentage coefficient - red')),
                ('percentage_white', models.FloatField(blank=True, null=True, verbose_name='Percentage coefficient - white')),
                ('time_stdev_all', models.FloatField(blank=True, null=True, verbose_name='Time coefficient standard deviation - all')),
                ('time_stdev_blue', models.FloatField(blank=True, null=True, verbose_name='Time coefficient standard deviation - blue')),
                ('time_stdev_red', models.FloatField(blank=True, null=True, verbose_name='Time coefficient standard deviation - red')),
                ('time_stdev_white', models.FloatField(blank=True, null=True, verbose_name='Time coefficient standard deviation - white')),
                ('time_mean_all', models.FloatField(blank=True, null=True, verbose_name='Time coefficient mean - all')),
                ('time_mean_blue', models.FloatField(blank=True, null=True, verbose_name='Time coefficient mean - blue')),
                ('time_mean_red', models.FloatField(blank=True, null=True, verbose_name='Time coefficient mean - red')),
                ('time_mean_white', models.FloatField(blank=True, null=True, verbose_name='Time coefficient mean - white')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.Experiment')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='trial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v2.Trial'),
        ),
    ]
