# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'Survey', 'verbose_name_plural': 'Surveys'},
        ),
        migrations.AlterModelOptions(
            name='trial',
            options={'verbose_name': 'Trial', 'verbose_name_plural': 'Trials'},
        ),
    ]
