# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='trial',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api_v2.Trial'),
            preserve_default=False,
        ),
    ]
