# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0002_auto_20161231_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='count_all',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Count click events - all', null=True, verbose_name='C'),
        ),
        migrations.AddField(
            model_name='trial',
            name='count_blue',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Count click events - blue', null=True, verbose_name='CB'),
        ),
        migrations.AddField(
            model_name='trial',
            name='count_red',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Count click events - red', null=True, verbose_name='CR'),
        ),
        migrations.AddField(
            model_name='trial',
            name='count_white',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Count click events - white', null=True, verbose_name='CW'),
        ),
        migrations.AddField(
            model_name='trial',
            name='percentage_all',
            field=models.FloatField(blank=True, help_text='Percentage Coefficient - all', null=True, verbose_name='P'),
        ),
        migrations.AddField(
            model_name='trial',
            name='percentage_blue',
            field=models.FloatField(blank=True, help_text='Percentage Coefficient - blue', null=True, verbose_name='PB'),
        ),
        migrations.AddField(
            model_name='trial',
            name='percentage_red',
            field=models.FloatField(blank=True, help_text='Percentage Coefficient - red', null=True, verbose_name='PR'),
        ),
        migrations.AddField(
            model_name='trial',
            name='percentage_white',
            field=models.FloatField(blank=True, help_text='Percentage Coefficient - white', null=True, verbose_name='PW'),
        ),
        migrations.AddField(
            model_name='trial',
            name='time_mean_all',
            field=models.FloatField(blank=True, help_text='Time Coefficient Mean - all', null=True, verbose_name='TM'),
        ),
        migrations.AddField(
            model_name='trial',
            name='time_mean_blue',
            field=models.FloatField(blank=True, help_text='Time Coefficient Mean - blue', null=True, verbose_name='TMB'),
        ),
        migrations.AddField(
            model_name='trial',
            name='time_mean_red',
            field=models.FloatField(blank=True, help_text='Time Coefficient Mean - red', null=True, verbose_name='TMR'),
        ),
        migrations.AddField(
            model_name='trial',
            name='time_mean_white',
            field=models.FloatField(blank=True, help_text='Time Coefficient Mean - white', null=True, verbose_name='TMW'),
        ),
        migrations.AddField(
            model_name='trial',
            name='time_stdev_all',
            field=models.FloatField(blank=True, help_text='Time Coefficient Standard Deviation - all', null=True, verbose_name='TSD'),
        ),
        migrations.AddField(
            model_name='trial',
            name='time_stdev_blue',
            field=models.FloatField(blank=True, help_text='Time Coefficient Standard Deviation - blue', null=True, verbose_name='TSDB'),
        ),
        migrations.AddField(
            model_name='trial',
            name='time_stdev_red',
            field=models.FloatField(blank=True, help_text='Time Coefficient Standard Deviation - red', null=True, verbose_name='TSDR'),
        ),
        migrations.AddField(
            model_name='trial',
            name='time_stdev_white',
            field=models.FloatField(blank=True, help_text='Time Coefficient Standard Deviation - white', null=True, verbose_name='TSDW'),
        ),
    ]
