# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0003_auto_20161231_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_valid',
            field=models.NullBooleanField(db_index=True, default=None, verbose_name='Action'),
        ),
    ]
