# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0003_auto_20161230_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='participant',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='participant',
            new_name='uid',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='experiment',
        ),
        migrations.AddField(
            model_name='survey',
            name='email',
            field=models.EmailField(db_index=True, default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='trial',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api_v2.Trial'),
            preserve_default=False,
        ),
    ]
