# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0004_auto_20161230_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Datetime')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('method', models.CharField(max_length=10, verbose_name='Method')),
                ('data', models.TextField(blank=True, null=True, verbose_name='Data')),
            ],
        ),
        migrations.DeleteModel(
            name='Experiment',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='seconds',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='trial',
            new_name='attempt',
        ),
        migrations.AddField(
            model_name='trial',
            name='regularity',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Click every X seconds'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trial',
            name='timeout',
            field=models.FloatField(default=30.0, verbose_name='Timeout in seconds per color'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='action',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(db_index=True, verbose_name='Datetime'),
        ),
        migrations.AlterField(
            model_name='event',
            name='target',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Target'),
        ),
        migrations.AlterField(
            model_name='event',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.Trial', verbose_name='Trial'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='condition',
            field=models.CharField(max_length=50, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='datetime',
            field=models.DateTimeField(verbose_name='Datetime'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='gender',
            field=models.CharField(max_length=50, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='rhythm',
            field=models.CharField(max_length=50, verbose_name='Rhythm'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.Trial', verbose_name='Trial'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='colors',
            field=models.CharField(max_length=50, verbose_name='Color order'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='device',
            field=models.CharField(max_length=50, verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='end',
            field=models.DateTimeField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='location',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Experiment location'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='polarization',
            field=models.CharField(max_length=50, verbose_name='Device polarization'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='start',
            field=models.DateTimeField(db_index=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='uid',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='User ID'),
        ),
    ]
