# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0004_event_is_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_index=True, verbose_name='Datetime')),
                ('color', models.CharField(db_index=True, max_length=50, verbose_name='Target')),
                ('is_valid', models.NullBooleanField(db_index=True, default=None, verbose_name='Is Valid?')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.Trial', verbose_name='Trial')),
            ],
            options={
                'verbose_name': 'Click',
                'verbose_name_plural': 'Click',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='is_valid',
            field=models.NullBooleanField(db_index=True, default=None, verbose_name='Is Valid?'),
        ),
    ]
