# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0005_auto_20161231_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial',
            old_name='start',
            new_name='start_datetime',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='end',
            new_name='end_datetime',
        ),
        migrations.AlterField(
            model_name='trial',
            name='attempt',
            field=models.PositiveSmallIntegerField(db_index=True, verbose_name='Which trial'),
        ),
    ]
