# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0005_auto_20161231_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_valid',
        ),
    ]
