# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0006_remove_event_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='percentage_all',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage Coefficient - all', max_digits=3, null=True, verbose_name='P'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='percentage_blue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage Coefficient - blue', max_digits=3, null=True, verbose_name='PB'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='percentage_red',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage Coefficient - red', max_digits=3, null=True, verbose_name='PR'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='percentage_white',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage Coefficient - white', max_digits=3, null=True, verbose_name='PW'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='regularity',
            field=models.PositiveSmallIntegerField(help_text='Click every X seconds', verbose_name='Regularity'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='time_mean_all',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Time Coefficient Mean - all', max_digits=3, null=True, verbose_name='TM'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='time_mean_blue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Time Coefficient Mean - blue', max_digits=3, null=True, verbose_name='TMB'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='time_mean_red',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Time Coefficient Mean - red', max_digits=3, null=True, verbose_name='TMR'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='time_mean_white',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Time Coefficient Mean - white', max_digits=3, null=True, verbose_name='TMW'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='time_stdev_all',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Time Coefficient Standard Deviation - all', max_digits=3, null=True, verbose_name='TSD'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='time_stdev_blue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Time Coefficient Standard Deviation - blue', max_digits=3, null=True, verbose_name='TSDB'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='time_stdev_red',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Time Coefficient Standard Deviation - red', max_digits=3, null=True, verbose_name='TSDR'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='time_stdev_white',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Time Coefficient Standard Deviation - white', max_digits=3, null=True, verbose_name='TSDW'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='timeout',
            field=models.DecimalField(decimal_places=2, help_text='Seconds per color', max_digits=3, verbose_name='Timeout'),
        ),
    ]
