# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0006_auto_20161231_1101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='count_all',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='count_blue',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='count_red',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='count_white',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='percentage_all',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='percentage_blue',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='percentage_red',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='percentage_white',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='time_mean_all',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='time_mean_blue',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='time_mean_red',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='time_mean_white',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='time_stdev_all',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='time_stdev_blue',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='time_stdev_red',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='time_stdev_white',
        ),
        migrations.AlterField(
            model_name='trial',
            name='attempt',
            field=models.PositiveSmallIntegerField(db_index=True, verbose_name='Attempt'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='end_datetime',
            field=models.DateTimeField(verbose_name='End datetime'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='location',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='polarization',
            field=models.CharField(max_length=50, verbose_name='Polarization'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='regularity',
            field=models.PositiveSmallIntegerField(help_text='Click every X seconds', verbose_name='Reqularity'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='start_datetime',
            field=models.DateTimeField(db_index=True, verbose_name='Start datetime'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='timeout',
            field=models.FloatField(help_text='Seconds per color', verbose_name='Timeout'),
        ),
    ]
