# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0007_auto_20170101_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='percentage_all',
            field=models.FloatField(blank=True, help_text='Percentage Coefficient - all', null=True, verbose_name='P'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='percentage_blue',
            field=models.FloatField(blank=True, help_text='Percentage Coefficient - blue', null=True, verbose_name='PB'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='percentage_red',
            field=models.FloatField(blank=True, help_text='Percentage Coefficient - red', null=True, verbose_name='PR'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='percentage_white',
            field=models.FloatField(blank=True, help_text='Percentage Coefficient - white', null=True, verbose_name='PW'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='time_mean_all',
            field=models.FloatField(blank=True, help_text='Time Coefficient Mean - all', null=True, verbose_name='TM'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='time_mean_blue',
            field=models.FloatField(blank=True, help_text='Time Coefficient Mean - blue', null=True, verbose_name='TMB'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='time_mean_red',
            field=models.FloatField(blank=True, help_text='Time Coefficient Mean - red', null=True, verbose_name='TMR'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='time_mean_white',
            field=models.FloatField(blank=True, help_text='Time Coefficient Mean - white', null=True, verbose_name='TMW'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='time_stdev_all',
            field=models.FloatField(blank=True, help_text='Time Coefficient Standard Deviation - all', null=True, verbose_name='TSD'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='time_stdev_blue',
            field=models.FloatField(blank=True, help_text='Time Coefficient Standard Deviation - blue', null=True, verbose_name='TSDB'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='time_stdev_red',
            field=models.FloatField(blank=True, help_text='Time Coefficient Standard Deviation - red', null=True, verbose_name='TSDR'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='time_stdev_white',
            field=models.FloatField(blank=True, help_text='Time Coefficient Standard Deviation - white', null=True, verbose_name='TSDW'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='timeout',
            field=models.FloatField(help_text='Seconds per color', verbose_name='Timeout'),
        ),
    ]
