# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0009_trial_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='time_regularity_series',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Time Regularity Series'),
        ),
    ]
