# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0010_trial_time_regularity_series'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='click',
            options={'ordering': ['datetime'], 'verbose_name': 'Click', 'verbose_name_plural': 'Click'},
        ),
        migrations.AlterField(
            model_name='trial',
            name='count_all',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='count_blue',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Count - blue'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='count_red',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Count - red'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='count_white',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Count - white'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='percentage_all',
            field=models.FloatField(blank=True, null=True, verbose_name='Tempo'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='percentage_blue',
            field=models.FloatField(blank=True, null=True, verbose_name='Tempo - blue'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='percentage_red',
            field=models.FloatField(blank=True, null=True, verbose_name='Tempo - red'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='percentage_white',
            field=models.FloatField(blank=True, null=True, verbose_name='Tempo - white'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='time_mean_all',
            field=models.FloatField(blank=True, null=True, verbose_name='Interval'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='time_mean_blue',
            field=models.FloatField(blank=True, null=True, verbose_name='Interval - blue'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='time_mean_red',
            field=models.FloatField(blank=True, null=True, verbose_name='Interval - red'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='time_mean_white',
            field=models.FloatField(blank=True, null=True, verbose_name='Interval - white'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='time_stdev_all',
            field=models.FloatField(blank=True, null=True, verbose_name='Regularity'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='time_stdev_blue',
            field=models.FloatField(blank=True, null=True, verbose_name='Regularity - blue'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='time_stdev_red',
            field=models.FloatField(blank=True, null=True, verbose_name='Regularity - red'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='time_stdev_white',
            field=models.FloatField(blank=True, null=True, verbose_name='Regularity - white'),
        ),
    ]
