# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 04:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0011_auto_20170225_0453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial',
            old_name='percentage_all',
            new_name='tempo_all',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='percentage_blue',
            new_name='tempo_blue',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='percentage_red',
            new_name='tempo_red',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='percentage_white',
            new_name='tempo_white',
        ),
    ]
