# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 04:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0012_auto_20170225_0455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial',
            old_name='time_stdev_all',
            new_name='regularity_all',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='time_stdev_blue',
            new_name='regularity_blue',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='time_stdev_red',
            new_name='regularity_red',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='time_stdev_white',
            new_name='regularity_white',
        ),
    ]
