# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0014_auto_20170225_0501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial',
            old_name='time_regularity_series',
            new_name='time_between_clicks',
        ),
    ]
