# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0015_auto_20170225_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='time_between_clicks',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Time between clicks'),
        ),
    ]
