# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0016_auto_20170225_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='bp_diastolic',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Blood Pressure DIA'),
        ),
        migrations.AddField(
            model_name='survey',
            name='bp_systolic',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Blood Pressure SYS'),
        ),
        migrations.AddField(
            model_name='survey',
            name='heart_rate',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Heart Rate'),
        ),
        migrations.AddField(
            model_name='survey',
            name='sleep_hours',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Sleep Hours'),
        ),
        migrations.AddField(
            model_name='survey',
            name='sleep_minutes',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Sleep Minutes'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='datetime',
            field=models.DateTimeField(db_index=True, verbose_name='Datetime'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='rhythm',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Rhythm'),
        ),
    ]
