# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0018_auto_20170828_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='rhythm',
            field=models.CharField(blank=True, default=None, editable=False, max_length=50, null=True, verbose_name='Rhythm'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='attempt',
            field=models.PositiveSmallIntegerField(blank=True, default=True, null=True, verbose_name='Attempt'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='location',
            field=models.CharField(max_length=50, verbose_name='Location'),
        ),
    ]
