# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0019_auto_20170828_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='condition',
            field=models.CharField(choices=[('rested', 'Well rested'), ('normal', 'Normal'), ('tired', 'Tired')], max_length=50, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], max_length=50, verbose_name='Gender'),
        ),
    ]
