# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0021_survey_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='heart_rate',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='bpm', null=True, verbose_name='Heart Rate'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, help_text='Celsius', max_digits=3, null=True, verbose_name='Temperature'),
        ),
    ]
