# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0022_auto_20170828_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='time',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('evening', 'Evening'), ('other', 'Other')], default=None, max_length=30, null=True, verbose_name='Time'),
        ),
    ]
