# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0024_survey_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='http_request_sha1',
            field=models.CharField(blank=True, default=None, max_length=40, null=True, unique=True, verbose_name='SHA1'),
        ),
    ]
