# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0025_trial_http_request_sha1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='http_request_sha1',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=40, null=True, unique=True, verbose_name='SHA1'),
        ),
    ]
